# Generated by Django 6.0.3 on 2026-03-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('PACIENTE_ACOMPANHANTE', 'Paciente e Acompanhante'), ('PACIENTE_DIETA_LIQUIDA', 'Paciente Dieta Líquida'), ('PACIENTE_BEBIDA', 'Paciente Bebida'), ('FUNCIONARIOS', 'Funcionários')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefeicaoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes_dia', to='refeicoes.refeicoes')),
            ],
            options={
                'unique_together': {('data', 'refeicao')},
            },
        ),
    ]
