# Generated by Django 6.0.1 on 2026-03-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('refeicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refeicaodia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
