# Generated by Django 6.0.1 on 2026-03-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0002_refeicaodia_empresa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refeicaodia',
            unique_together=set(),
        ),
    ]
