# Generated by Django 6.0.3 on 2026-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refeicoes', '0003_alter_refeicaodia_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicaodia',
            name='data',
            field=models.DateField(db_index=True),
        ),
    ]
