# Generated by Django 6.0.3 on 2026-04-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20),
        ),
    ]
