# Generated by Django 6.0.3 on 2026-04-08 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Sede, Filial, Home Office', max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=4)),
                ('cep', models.CharField(max_length=12)),
                ('tipo', models.CharField(choices=[('intern', 'Interno'), ('extern', 'Externo'), ('remote', 'Home Office')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo_vinculado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='Cadastro de Pessoa Física (CPF)')),
                ('rg', models.CharField(max_length=10, verbose_name='Registro Geral (RG)')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('naturalidade', models.CharField(max_length=100, verbose_name='Natrualidade')),
                ('nome_mae', models.CharField(max_length=200, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=200, verbose_name='Nome do Pai')),
                ('genero', models.CharField(blank=True, choices=[('PREFIRO_NAO_INFORMAR', 'Prefiro não informar'), ('MULHER', 'Mulher'), ('HOMEM', 'Homem'), ('TRAVESTI', 'Travesti'), ('NAO_BINARIO', 'Não Binário'), ('AGENERO', 'Agênero'), ('INTERSEXO', 'Intersexo')], default='PREFIRO_NAO_INFORMAR', max_length=30, verbose_name='Gênero')),
                ('ctps_digital', models.CharField(max_length=14, unique=True, verbose_name='CTPS Digital (CPF)')),
                ('titulo_eleitoral', models.CharField(blank=True, max_length=14, null=True)),
                ('certificado_reservista', models.CharField(blank=True, max_length=20, null=True, verbose_name='Certificado Reservista')),
                ('pis_pasep_nis', models.CharField(max_length=14, verbose_name='PIS/PASEP/NIS')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base')),
                ('perido_pagamento', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], default='MENSAL', max_length=12, verbose_name='Periocidade do Pagamento')),
                ('tipo_contrato', models.CharField(choices=[('INDETERMINADO', 'Indeterminado'), ('DETERMINADO', 'Determinado'), ('EXPERIENCIA', 'Experiência'), ('TEMPORARIO', 'Temporário'), ('INTERMITENTE', 'Intermitente'), ('ESTAGIO', 'Estágio')], default='INDETERMINADO', max_length=20, verbose_name='Tipo de Contrato')),
                ('jornada_trabalho_dia_semana', models.CharField(max_length=10)),
                ('jornada_trabalho_hora_entrada', models.TimeField()),
                ('jornada_trabalho_hora_saida', models.TimeField()),
                ('tipo_aso', models.CharField(choices=[('A', 'Admissional'), ('P', 'Periódico'), ('R', 'Retorno ao trabalho'), ('M', 'Mudança de Risco'), ('D', 'Demissional')], max_length=100, verbose_name='Tipo do ASO')),
                ('data_realizacao_aso', models.DateField(verbose_name='Data da realização do exame ASO')),
                ('parecer', models.CharField(choices=[('APTO', 'Apto'), ('INAPTO', 'Inapto')], max_length=8, verbose_name='Parecer Médico')),
                ('nome_medico', models.CharField(max_length=200, verbose_name='Nome do Médico')),
                ('numero_crm', models.CharField(max_length=7, verbose_name='Número Conselhor Regional de Medicina (CRM)')),
                ('uf_crm', models.CharField(max_length=2, verbose_name='UF - CRM')),
                ('data_vencimento_aso', models.DateField(verbose_name='Data de Vencimento ASO')),
                ('foto_exame', models.FileField(blank=True, null=True, upload_to='gestao_pessoas/ASOS')),
                ('comprovante_escolaridade', models.FileField(blank=True, null=True, upload_to='gestao_pessoas/comprovante_escolaridade')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=15, verbose_name='Agência Bancária')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança')], max_length=20)),
                ('titular_conta', models.CharField(max_length=100, verbose_name='Titular da Conta')),
                ('cpf_cnpj_conta', models.CharField(max_length=20, verbose_name='CPF ou CNPJ da Conta')),
                ('declaracao_vale_transporte', models.FileField(blank=True, null=True, upload_to='gestao_pessoas/vale_transporte')),
                ('tem_dependentes', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_pessoas.cargo', verbose_name='Cargo')),
                ('usuario_auth', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_funcionario', to=settings.AUTH_USER_MODEL)),
                ('local_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao_pessoas.localtrabalho')),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dependente', models.CharField(max_length=200, verbose_name='Nome do dependente')),
                ('cpf_dependente', models.CharField(max_length=14, unique=True, verbose_name='Cadastro de Pessoa Física (CPF) - Dependente')),
                ('data_nascimento_dependente', models.DateField(verbose_name='Data de Nascimento - Dependente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='gestao_pessoas.funcionario')),
            ],
        ),
    ]
